### ISSUE TITLE
Problem with patched FW 1.4.0

### ISSUE THREAD

**Issue by oldtrapper** [BotoX/xiaomi-m365-firmware-patcher#11]
Rolling along without pushing trottle, no matter whether or not in the Range of KERS activated, strange behaviour when accellerating again: For a splitsecond no accelleration at all and then harsh beat in the motor, when accelleration starts. It is reproducable every time, Actual speed does not make any difference. Same at 4 or at 24 km/h. Does not occur with FW 1.3.8 ... there is a smooth, nevertheless puncy acceleration with my parameters ... mainly Motor Power Constant 40.000.

For now I stick to 1.3.8. How can I acchieve this smooth behaviour on FW 1.4.0?

**Comment by BotoX** [comment]
The engine is turned off in 1.4.0 which is what causes this I guess. Nothing that I can fix really.
