### ISSUE TITLE
Can I install the new one over the old one?

### ISSUE THREAD

**Issue by czaku** [BotoX/xiaomi-m365-firmware-patcher#17]
HI,

Using https://m365.botox.bz - excuse my complete basic knowledge of the firmware world :)

I have updated my scooter to 1.4.1, can I still produce a bin file using that website based on 1.4.0 or 1.3.8 and flash the firmware on my scooter? Or that won't work / will break things?

Thanks... :)

**Comment by MrSnowball-dev** [comment]
No, you can't go back from 1.4.1, this one blocks the firmware. To roll back you should completely reset your scooter's with ST-Link.
