### ISSUE TITLE
Open .bin 

### ISSUE THREAD

**Issue by mrick33** [BotoX/xiaomi-m365-firmware-patcher#21]
that will be great to have the possibility to open or read an existing custom patched file .bin or official with botox patcher
like a "load .bin" 

if not, is there a simple way to open or read a .bin file ?

cordially

**Comment by BotoX** [comment]
this tool applies patches on the original firmware, you can also open modified firmware with it but the patches may fail if they were already applied
i don't understand the point of it though

**Comment by Ghostfly** [comment]
Imagine you find a mysterious patched firmware and want to know what kind of settings are set, I think it could be interesting, but not really important
