### ISSUE TITLE
Activate KERS based on mechanical brakes push

### ISSUE THREAD

**Issue by beckos** [BotoX/xiaomi-m365-firmware-patcher#23]
I wonder if is possible to add a patch feature to the firmware, where KERS would be activated by mechanical brake push. That means that, if pushed just slowly (mechanical action would not yet be applied, just the electric trigger inside brake lever would be actioned), it will be KERS (which should/would be set low) which will do the braking, so the regenerative braking will be manual, and not automatic. When auto, the roling based on inertia is slowed down and speed lost rather fast and that is anoying, whereas if activated by manual brake push, it would be authentic rgenerative braking on demand. Of course, enabling such a feature patch would mean to disable automatic entering of KERS, even if the speed threshold is set low.

**Comment by BotoX** [comment]
The brake lever already does that.
Just set KERS to a high value (like 40km/h) and use your brake lever for regenerative braking.
