### ISSUE TITLE
Power drop below 50% battery

### ISSUE THREAD

**Issue by marcinkunert** [BotoX/xiaomi-m365-firmware-patcher#25]
Some users (including me) noticed a significant power drop when the battery is at 50% or lower. This is supposedly a software feature introduced in 1.3.4. It would be nice to have an option to either disable it or set to a different value, like 20% or so.

**Comment by BotoX** [comment]
It is not a software feature, it's simply physics.
The battery voltage drops as it is depleted, thus the performance decreases as well.
