### ISSUE TITLE
Cruise Control - sound

### ISSUE THREAD

**Issue by Sharky1231** [BotoX/xiaomi-m365-firmware-patcher#47]
Is it possible to implement an adjustment to adjust or turn off sound when cruise control gets enabled?
Because I want to have cruise control enabled quite fast (after 3 seconds) but I dont want to be beeping around cyclists all the time, they are looking around, wondering what is happening, etc.

**Comment by BotoX** [comment]
Yeah that could be done I think. I'll see if I can take a look this week.

**Comment by openffchrome** [comment]
an option to disable the sound when turning on or off the m365 would be awesome also, i hate when everyone is wondering what is beeping :s thanks

**Comment by hoerbi1000** [comment]
i would also like a change for no sound :)

**Comment by BotoX** [comment]
Here you go, tested it only in my room, seems to work: https://m365beta.botox.bz/
Let me know if it works for you.

**Comment by hoerbi1000** [comment]
i will check it in the afternoon :)

**Comment by hoerbi1000** [comment]
Works ;)
