### ISSUE TITLE
auto-lock, unlock with power+brake+?

### ISSUE THREAD

**Issue by openffchrome** [BotoX/xiaomi-m365-firmware-patcher#53]
Hello it would be pretty nice if it was possible to lock the m365 without using a phone, eg locking it automatically after X minutes if not moving or by pressing a combination of buttons like power button+brake or something like that  and also there must be an similar feature to unlock it without using the phone by pressing power button+brake or maybe brake + Pushing power button multiple times?

not sure if it's possible, thanks !

**Comment by BotoX** [comment]
Adding additional features to the firmware is out of scope for this project, it's way too much effort because there's no source code.
I can only make small changes, remove stuff or change some values.
