### ISSUE TITLE
Speed cannot exceed 25Km/h using custom firmware 

### ISSUE THREAD

**Issue by yuan910715** [BotoX/xiaomi-m365-firmware-patcher#62]
Hello, My M365 scooter version is 1.5.1 BLE081 , after a have flash a BLE072 I can flash the custom  firmware from m365.botox.bz , I just patched the ' Maximum speed in Normal mode' and set to 33km/h , and patched 'Motor start speed' set to 1km/h. after flashed the bin , 'Motor start speed' is effective but the max speed didn't change, it's about 25-26km/h .I don't know why.
Thanks.

**Comment by BotoX** [comment]
Set it to max 30km/h and read the other issues.
