### ISSUE TITLE
Permanent changes to m365 flash?

### ISSUE THREAD

**Issue by Tommixoft** [BotoX/xiaomi-m365-firmware-patcher#7]
Im confused. I used your website made modified firmware, boot with eco mode by default.  Now i dont need this feature, so i installed default firmware with no mods - still boots in eco. 
Reflashed 2 different firmware versions -still boots with eco.
Used original flasher, installed your bin (from github not modified) still boots in eco mode. WTF? 

SO now the real issue is not even eco mode, but fact that maybe changes in FW stays forever no matter if i do upgrade stock fw.

**Comment by BotoX** [comment]
The firmware remembers the last state of the Eco Mode when you turn it off lol.
Turn off eco mode and then turn off the scooter. Start it again it should boot into normal mode.

**Comment by Tommixoft** [comment]
:DDDD oh that would be really lol :) thanks will test it.
