### ISSUE TITLE
Charging limit to prolong battery life

### ISSUE THREAD

**Issue by sellblue** [BotoX/xiaomi-m365-firmware-patcher#72]
Is it possible to set the maximum charging voltage to extend the battery lifetime? See detailed article: https://batteryuniversity.com/learn/article/how_to_prolong_lithium_based_batteries

**Comment by BotoX** [comment]
This is done by the charger
The motor controller has nothing to do with this.
The default cell voltage on the xiaomi is 4.15V, I charge my cells to 4.10V
The charger can be opened (YouTube) and the voltage can be adjusted slightly with a trim potentiometer.
The bms firmware can also be modified to limit the charge voltage earlier but that's out of scope for this project
