### ISSUE TITLE
Instant Mode Switch

### ISSUE THREAD

**Issue by oldtrapper** [BotoX/xiaomi-m365-firmware-patcher#9]
What is the effect of this parameter?

Initially I assumed it will change Normal to Eco Mode during a ride (whithout previously stopping) by dubbleclicking on the power switch. Instead mine (build date (02/2018) turns off cruise control  (and back on again).

**Comment by BotoX** [comment]
It will allow you to instantly switch from Normal -> Eco and vice versa while riding without having to touch the throttle.
So you're driving with cruise control and want to switch to Eco -> double press the power button and the scooter will instantly go to Eco mode and reduce its speed to 25km/h.

**Comment by oldtrapper** [comment]
ok, will give it a try again, thks
